### ISSUE TITLE
Hope to provide the official docker image

### ISSUE THREAD

**Issue by Dreamacro** [vi/websocat#154]
I've searched from https://hub.docker.com/search?q=websocat, but can't find an official docker image.

It would be helpful to have a github packages or dockerhub image to use this tool.

**Comment by vi** [comment]
I remember somebody contributing a [Dockerfile for Websocat](https://github.com/vi/websocat/blob/master/Dockerfile). Does it still work? (I don't use it myself).

**Comment by Dreamacro** [comment]
It broken but I can create a pull request to fixed it. If the build works, is it possible to add a github action to automatically generate an official docker image?

**Comment by vi** [comment]
Websocat does not currently use a CI (there was previously a travis-ci.org for checking commits, but now it is defunct). I typically build release artifacts on my laptop and build environment may be different each time.

Build reproducibility is planned for Websocat3. But if you contribute an updated Dockerfile and Github Actions configs for it (I never used myself Github Actions yet) then I will likely use it when creating releases; and pending release of Websocat 1.10.0 with some bugfixes will have a Docker Hub image.

**Comment by Dreamacro** [comment]
Okay, I would fix Dockerfile first, and then take a look at how the Github Actions work for the rust binary.

There are two options: push docker image to Docker Hub or Github Packages, but additional secrets need to be configured in the project

The example
```yaml
- name: Login to DockerHub
  uses: docker/login-action@v1
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}

- name: Login to Github Package
  uses: docker/login-action@v1
  with:
    registry: ghcr.io
    username: Dreamacro
    password: ${{ secrets.PACKAGE_TOKEN }}
```
